"""added new otp and phone fields

Revision ID: 1820efb39cb9
Revises: 001b4f9c5187
Create Date: 2025-10-21 15:51:55.919558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1820efb39cb9'
down_revision = '001b4f9c5187'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('otp_type', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("otp_type IN ('email', 'phone')", name='ck_otp_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'phone')
    op.drop_table('otps')
    # ### end Alembic commands ###
